services:
  injector-http-query:
    image: openaev/injector-http-query:latest
    environment:
      - OPENAEV_URL=${OPENAEV_URL}
      - OPENAEV_TOKEN=${OPENAEV_TOKEN}
      - INJECTOR_ID=${INJECTOR_ID}
      - INJECTOR_NAME=${INJECTOR_NAME}
      - INJECTOR_LOG_LEVEL=${INJECTOR_LOG_LEVEL}
    restart: always
