services:
  injector-teams:
    image: openaev/injector-teams:2.0.11
    environment:
      - OPENAEV_URL=http://localhost
      - OPENAEV_TOKEN=ChangeMe
      - INJECTOR_ID=ChangeMe
      - INJECTOR_NAME=Teams
      - INJECTOR_LOG_LEVEL=error
    restart: always
    depends_on:
      openaev:
        condition: service_healthy
