services:
  injector-shodan:
    image: openaev/injector-shodan:latest
    environment:
      - OPENAEV_URL=${OPENAEV_URL}
      - OPENAEV_TOKEN=${OPENAEV_TOKEN}
      - INJECTOR_ID=${INJECTOR_ID}
      - INJECTOR_NAME=${INJECTOR_NAME}
      - INJECTOR_LOG_LEVEL=${INJECTOR_LOG_LEVEL}
      - SHODAN_API_KEY=${SHODAN_API_KEY}
      - SHODAN_BASE_URL=${SHODAN_BASE_URL}
      - SHODAN_API_LEAKY_BUCKET_RATE=${SHODAN_API_LEAKY_BUCKET_RATE}
      - SHODAN_API_LEAKY_BUCKET_CAPACITY=${SHODAN_API_LEAKY_BUCKET_CAPACITY}
      - SHODAN_API_RETRY=${SHODAN_API_RETRY}
      - SHODAN_API_BACKOFF=${SHODAN_API_BACKOFF}
    restart: always
