[project]
name="injector_common"
version="1.0.0"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]


[tool.isort]
profile = "black"
known_local_folder = ["injector_common"]