version: '3.8'
services:
  injector-nuclei:
    image: openaev/injector-nuclei:2.0.8
    environment:
      - OPENAEV_URL=http://localhost
      - OPENAEV_TOKEN=ChangeMe
      - INJECTOR_ID=ChangeMe
      - INJECTOR_NAME=Nuclei
      - INJECTOR_LOG_LEVEL=WARN
    restart: always
    depends_on:
      openaev:
        condition: service_healthy
