[tool.poetry]
name = "openaev-nuclei-injector"
version = "2.0.14"
description = "An injector for running vulnerability scans with Nuclei"
authors = ["Filigran <contact@filigran.io>"]
license = "Apache-2.0"
readme = "README.md"
packages = [
    { include = "nuclei" }
]


[tool.poetry.dependencies]
python = "^3.11"
pyoaev = [
    { markers = "extra == 'prod' and extra != 'dev'", version = "2.0.14", source = "pypi"  },
    { markers = "extra == 'dev' and extra != 'prod'", path = "../../client-python", develop = true },
]
injector_common = { path = "../injector_common", develop = true }

[tool.poetry.extras]
prod = ["pyoaev"]
dev = ["pyoaev"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
known_local_folder = ["nuclei"]

[tool.cmw]
install-command = "poetry install --extras prod"
config-dump-command = "poetry run python -m nuclei.openaev_nuclei --dump-config-schema"
icon-path = "nuclei/img/nuclei.jpg"
