version: '3'
services:
  injector-nmap:
    image: openaev/injector-nmap:2.1.4
    environment:
      - OPENAEV_URL=http://localhost
      - OPENAEV_TOKEN=ChangeMe
      - INJECTOR_ID=ChangeMe
      - "INJECTOR_NAME=Nmap"
      - INJECTOR_LOG_LEVEL=error
    restart: always
