version: '3'
services:
  injector-aws:
    image: openaev/injector-aws:2.0.8
    environment:
      - OPENAEV_URL=http://localhost
      - OPENAEV_TOKEN=ChangeMe
      - INJECTOR_ID=ChangeMe
      - "INJECTOR_NAME=AWS"
      - INJECTOR_LOG_LEVEL=error
    restart: always